# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

# Create 2 jobs for running tests and linting with different Python versions

name: Deploy Master Flows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Add your jobs here
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m pytest test/test.py
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8
      - name: Deploy to Master
        run: |
          echo "Deploying to Master"
          echo "Deployed to Master"

